title: "Мой блог"
description: "Простой блог на GitHub Pages с Jekyll"
baseurl: "" # Если это основной сайт, оставь пустым
url: "https://berlandbor.github.io/BlogBerlandbor-/"
theme: minima # Встроенная тема Jekyll
